### ISSUE TITLE
Changelogs cannot be linked to Issues

### ISSUE THREAD

**Issue by matt-zach-s** [singer-io/tap-jira#10]
There is no data in the [changelogs](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-changelog-get) endpoint that I can use to join data from changelogs to the parent issue.

It looks like [here](https://github.com/singer-io/tap-jira/blob/master/tap_jira/streams.py#L144) the pertinent "issueIdOrKey" is input when requesting changelog data. 

Can we output the issue `id` in the changelog object as well? Doing so would help to connect this data to parent issue(s).

**Comment by nick-mccoy** [comment]
PR [11](https://github.com/singer-io/tap-jira/pull/11) addresses this issue.  I added a new issueId field to be the [changelogs](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-changelog-get) and [comments](https://developer.atlassian.com/cloud/jira/platform/rest/#api-api-2-issue-issueIdOrKey-comment-id-get) endpoints since they both need a way to link back to their parent issue.

There was also a bug that caused some changelogs to be missed during the sync.  The above PR fixes that as well
